### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by ahmutkadim** [mchlkpng/defold-mobilehtml5-typing#1]
I have tried the demo version and it does not work. Are you sure the library works? I have used an iPad and safari browser for trying it.

**Comment by mchlkpng** [comment]
really? well it had been tested on android, sadly i did not have an ios to test it on and because of the simplicity, i did not feel the need to set up an emulator. Could you show me the behavior?

**Comment by mchlkpng** [comment]
I have found the issue. It seems that the algorithm used to check for mobile does not include safari on iPads specifically. I'll get this fixed as soon as possible.

**Comment by ahmutkadim** [comment]
Thanks so much, I saw your reply a bit late. Thanks so much for showing attention to, and developing this extension. I really appreciate it.

**Comment by mchlkpng** [comment]
Alright, in the newest release I had fixed the issue. The issue was that the userAgent in the browser for apple devices have been changed to look identical to the Mac's, causing the browser not to recognize it as mobile.
